# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
cache: packages

install:
    # Install TileDB
    - git clone https://github.com/TileDB-Inc/TileDB /tmp/TileDB
    - pushd /tmp/TileDB
    - git checkout 1.2.0
    - mkdir build
    - pushd build
    - ../scripts/install-deps.sh
    - ../bootstrap --enable-verbose
    - sudo make install -j4
    - popd
    - popd

    # Install R package deps 
    - R -e 'install.packages("devtools")'
    - R -e 'devtools::install_deps(dep = T)'

script:
    # Build and Test R package
    - R CMD INSTALL --no-multiarch --with-keep.source --configure-args='--with-tiledb=/tmp/TileDB/dist' TileDB-R
    - R -e 'library(devtools)'
    - R -e 'devtools::test()'
    
    # - R CMD BUILD .
    # - R CMD check *tar.gz
